import type { NextPage } from "next";
import { useState } from "react";
import Head from "next/head";
import UserPicker from "../components/UserPicker";
import UserRegister from "../components/UserRegister";
import Game from "../components/Game";

const Home: NextPage = () => {
  const [who, setWho] = useState(null);

  return (
    <div className="flex flex-col items-center">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {who ? (
        <Game who={who} setWho={setWho} />
      ) : (
        <>
          <UserPicker setWho={setWho} />
          <UserRegister />
        </>
      )}
    </div>
  );
};

export default Home;
